name: yt_weekly_100
description: "Top 100 Youtube Videos This Week."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.2.2
  provider: ^6.0.0
  http: ^1.2.0 # for fetching web APIs
  flutter_dotenv: ^5.1.0 # for .env usage
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9 # for Firebase Authentication
  fluttertoast: ^8.2.4
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.15.9
  url_launcher: ^6.2.5
  responsive_builder: ^0.7.0
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
